name: "Colony361"
description: "Many groups came together to form our great republic. First among equals, was Colony361. Some believe it was the brain child of an ex-military man, and others say it was just a collaborative accident. Either way, it conducted itself on 3 simple principles. One. the re-generation of dead space. Two. the collaboration & hybridization of disciplines. Three. the construction of your own happy place."

domain: "www.afrobananarepublic.com"
static_path: "//afrobanana.s3-external-3.amazonaws.com/colony361/static/"
